SELECT * FROM engines;
SELECT * FROM teams;
SELECT * FROM pilots;
SELECT * FROM circuits;
SELECT * FROM grand_prix;
SELECT * FROM tyres;
SELECT * FROM free_practices;
SELECT * FROM qualys;
SELECT * FROM races;